### ISSUE TITLE
Add a production mode that disables type checking?

### ISSUE THREAD

**Issue by bluefeet** [bluefeet/o-js#7]
Seems that it would be useful to add a mode that disables all type checking. This would speed up performance of o.js considerably and could be used in a production environment where speed matters when all type-errors have been stamped out during testing.

Similar in concept to logging mechanisms that stop logging in production where the small footprint of logging actually impacts performance.

Note: Need to actually prove that this is useful before implementing.

**Comment by singingfish** [comment]
Smells risky to me :)

**Comment by bluefeet** [comment]
This is done, included in `0.1.0`.  May be risky, but all code is risky in the wrong hands.
